import { DEFAULT as DEFAULT_COLOR, COLOR, DEFAULT_BACKGROUND as DEFAULT_BACKGROUND_COLOR } from "./colors";
import { DEFAULT as DEFAULT_STATE, COLORED as COLORED_STATE } from "./states";

export {
  DEFAULT_COLOR,
  COLOR,
  DEFAULT_BACKGROUND_COLOR,
  DEFAULT_STATE,
  COLORED_STATE
};